package client

// this file is autogenerated for Account record type

import (
	"errors"
	"log"

	"github.com/alexey-mavrin/graduate-2/internal/common"
	"github.com/alexey-mavrin/graduate-2/internal/store"
)

func (c *Client) cacheDeleteAccount(id int64) error {
	if c.CacheFile == "" {
		return nil
	}
	cache, err := store.NewStore()
	if err != nil {
		log.Printf("cannot get local store: %v", err)
		return err
	}
	err = cache.DeleteAccount(c.UserName, id)
	if err != nil {
		return err
	}
	return nil
}

func (c *Client) cacheAccount(storeID int64, record common.Account) error {
	if c.CacheFile == "" {
		return nil
	}
	cache, err := store.NewStore()
	if err != nil {
		log.Printf("cannot get local store: %v", err)
		return err
	}

	_, err = cache.AddUser(common.User{
		Name: c.UserName,
	})
	if err != nil && err != store.ErrAlreadyExists {
		return err
	}

	records, err := cache.ListAccounts(c.UserName)

	for id := range records {
		if records[id].Name != record.Name {
			continue
		}
		if id != storeID {
			return errors.New("local cache is out of sync")
		}
		err = cache.DeleteAccount(c.UserName, id)
		if err != nil {
			return err
		}
		break
	}

	err = cache.StoreAccountID(storeID, c.UserName, record)
	if err != nil {
		return err
	}
	return nil
}

func (c *Client) cacheGetAccount(id int64) (common.Account, error) {
	if c.CacheFile == "" {
		return common.Account{}, nil
	}
	cache, err := store.NewStore()
	if err != nil {
		log.Printf("cannot get local store: %v", err)
		return common.Account{}, err
	}
	return cache.GetAccount(c.UserName, id)
}

func (c *Client) cacheListAccounts() (common.Accounts, error) {
	records := make(common.Accounts)
	if c.CacheFile == "" {
		return records, nil
	}
	cache, err := store.NewStore()
	if err != nil {
		log.Printf("cannot get local store: %v", err)
		return records, err
	}
	return cache.ListAccounts(c.UserName)
}
