package client

// this file is autogenerated for Note record type

import (
	"errors"
	"log"

	"github.com/alexey-mavrin/graduate-2/internal/common"
	"github.com/alexey-mavrin/graduate-2/internal/store"
)

func (c *Client) cacheDeleteNote(id int64) error {
	if c.CacheFile == "" {
		return nil
	}
	cache, err := store.NewStore()
	if err != nil {
		log.Printf("cannot get local store: %v", err)
		return err
	}
	err = cache.DeleteNote(c.UserName, id)
	if err != nil {
		return err
	}
	return nil
}

func (c *Client) cacheNote(storeID int64, record common.Note) error {
	if c.CacheFile == "" {
		return nil
	}
	cache, err := store.NewStore()
	if err != nil {
		log.Printf("cannot get local store: %v", err)
		return err
	}

	_, err = cache.AddUser(common.User{
		Name: c.UserName,
	})
	if err != nil && err != store.ErrAlreadyExists {
		return err
	}

	records, err := cache.ListNotes(c.UserName)

	for id := range records {
		if records[id].Name != record.Name {
			continue
		}
		if id != storeID {
			return errors.New("local cache is out of sync")
		}
		err = cache.DeleteNote(c.UserName, id)
		if err != nil {
			return err
		}
		break
	}

	err = cache.StoreNoteID(storeID, c.UserName, record)
	if err != nil {
		return err
	}
	return nil
}

func (c *Client) cacheGetNote(id int64) (common.Note, error) {
	if c.CacheFile == "" {
		return common.Note{}, nil
	}
	cache, err := store.NewStore()
	if err != nil {
		log.Printf("cannot get local store: %v", err)
		return common.Note{}, err
	}
	return cache.GetNote(c.UserName, id)
}

func (c *Client) cacheListNotes() (common.Notes, error) {
	records := make(common.Notes)
	if c.CacheFile == "" {
		return records, nil
	}
	cache, err := store.NewStore()
	if err != nil {
		log.Printf("cannot get local store: %v", err)
		return records, err
	}
	return cache.ListNotes(c.UserName)
}
